// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/ports/metrics_collector.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/ports/metrics_collector.go -destination=mocks/mock_metrics_collector.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsCollector is a mock of MetricsCollector interface.
type MockMetricsCollector struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCollectorMockRecorder
	isgomock struct{}
}

// MockMetricsCollectorMockRecorder is the mock recorder for MockMetricsCollector.
type MockMetricsCollectorMockRecorder struct {
	mock *MockMetricsCollector
}

// NewMockMetricsCollector creates a new mock instance.
func NewMockMetricsCollector(ctrl *gomock.Controller) *MockMetricsCollector {
	mock := &MockMetricsCollector{ctrl: ctrl}
	mock.recorder = &MockMetricsCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsCollector) EXPECT() *MockMetricsCollectorMockRecorder {
	return m.recorder
}

// IncrementProductsCreated mocks base method.
func (m *MockMetricsCollector) IncrementProductsCreated() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementProductsCreated")
}

// IncrementProductsCreated indicates an expected call of IncrementProductsCreated.
func (mr *MockMetricsCollectorMockRecorder) IncrementProductsCreated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementProductsCreated", reflect.TypeOf((*MockMetricsCollector)(nil).IncrementProductsCreated))
}

// IncrementProductsDeleted mocks base method.
func (m *MockMetricsCollector) IncrementProductsDeleted() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementProductsDeleted")
}

// IncrementProductsDeleted indicates an expected call of IncrementProductsDeleted.
func (mr *MockMetricsCollectorMockRecorder) IncrementProductsDeleted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementProductsDeleted", reflect.TypeOf((*MockMetricsCollector)(nil).IncrementProductsDeleted))
}

// IncrementRequestCount mocks base method.
func (m *MockMetricsCollector) IncrementRequestCount(method, endpoint, status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementRequestCount", method, endpoint, status)
}

// IncrementRequestCount indicates an expected call of IncrementRequestCount.
func (mr *MockMetricsCollectorMockRecorder) IncrementRequestCount(method, endpoint, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRequestCount", reflect.TypeOf((*MockMetricsCollector)(nil).IncrementRequestCount), method, endpoint, status)
}

// IncrementTransactionRetry mocks base method.
func (m *MockMetricsCollector) IncrementTransactionRetry() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementTransactionRetry")
}

// IncrementTransactionRetry indicates an expected call of IncrementTransactionRetry.
func (mr *MockMetricsCollectorMockRecorder) IncrementTransactionRetry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementTransactionRetry", reflect.TypeOf((*MockMetricsCollector)(nil).IncrementTransactionRetry))
}

// IncrementTransactionRetryFailed mocks base method.
func (m *MockMetricsCollector) IncrementTransactionRetryFailed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementTransactionRetryFailed")
}

// IncrementTransactionRetryFailed indicates an expected call of IncrementTransactionRetryFailed.
func (mr *MockMetricsCollectorMockRecorder) IncrementTransactionRetryFailed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementTransactionRetryFailed", reflect.TypeOf((*MockMetricsCollector)(nil).IncrementTransactionRetryFailed))
}

// IncrementTransactionRetrySuccess mocks base method.
func (m *MockMetricsCollector) IncrementTransactionRetrySuccess() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementTransactionRetrySuccess")
}

// IncrementTransactionRetrySuccess indicates an expected call of IncrementTransactionRetrySuccess.
func (mr *MockMetricsCollectorMockRecorder) IncrementTransactionRetrySuccess() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementTransactionRetrySuccess", reflect.TypeOf((*MockMetricsCollector)(nil).IncrementTransactionRetrySuccess))
}

// RecordBatchSize mocks base method.
func (m *MockMetricsCollector) RecordBatchSize(operation string, size int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordBatchSize", operation, size)
}

// RecordBatchSize indicates an expected call of RecordBatchSize.
func (mr *MockMetricsCollectorMockRecorder) RecordBatchSize(operation, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBatchSize", reflect.TypeOf((*MockMetricsCollector)(nil).RecordBatchSize), operation, size)
}

// RecordDatabaseQueryDuration mocks base method.
func (m *MockMetricsCollector) RecordDatabaseQueryDuration(duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDatabaseQueryDuration", duration)
}

// RecordDatabaseQueryDuration indicates an expected call of RecordDatabaseQueryDuration.
func (mr *MockMetricsCollectorMockRecorder) RecordDatabaseQueryDuration(duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDatabaseQueryDuration", reflect.TypeOf((*MockMetricsCollector)(nil).RecordDatabaseQueryDuration), duration)
}

// RecordOutboxEventProcessed mocks base method.
func (m *MockMetricsCollector) RecordOutboxEventProcessed(eventType, status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordOutboxEventProcessed", eventType, status)
}

// RecordOutboxEventProcessed indicates an expected call of RecordOutboxEventProcessed.
func (mr *MockMetricsCollectorMockRecorder) RecordOutboxEventProcessed(eventType, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordOutboxEventProcessed", reflect.TypeOf((*MockMetricsCollector)(nil).RecordOutboxEventProcessed), eventType, status)
}

// RecordOutboxRetryAttempt mocks base method.
func (m *MockMetricsCollector) RecordOutboxRetryAttempt(eventType string, attempt int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordOutboxRetryAttempt", eventType, attempt)
}

// RecordOutboxRetryAttempt indicates an expected call of RecordOutboxRetryAttempt.
func (mr *MockMetricsCollectorMockRecorder) RecordOutboxRetryAttempt(eventType, attempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordOutboxRetryAttempt", reflect.TypeOf((*MockMetricsCollector)(nil).RecordOutboxRetryAttempt), eventType, attempt)
}

// RecordRabbitMQPublishDuration mocks base method.
func (m *MockMetricsCollector) RecordRabbitMQPublishDuration(duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRabbitMQPublishDuration", duration)
}

// RecordRabbitMQPublishDuration indicates an expected call of RecordRabbitMQPublishDuration.
func (mr *MockMetricsCollectorMockRecorder) RecordRabbitMQPublishDuration(duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRabbitMQPublishDuration", reflect.TypeOf((*MockMetricsCollector)(nil).RecordRabbitMQPublishDuration), duration)
}

// RecordRequestDuration mocks base method.
func (m *MockMetricsCollector) RecordRequestDuration(method, endpoint, status string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRequestDuration", method, endpoint, status, duration)
}

// RecordRequestDuration indicates an expected call of RecordRequestDuration.
func (mr *MockMetricsCollectorMockRecorder) RecordRequestDuration(method, endpoint, status, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRequestDuration", reflect.TypeOf((*MockMetricsCollector)(nil).RecordRequestDuration), method, endpoint, status, duration)
}
