// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/ports/outbox_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/ports/outbox_repository.go -destination=mocks/mock_outbox_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	ports "product_service/products/internal/usecase/ports"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// CheckIdempotencyKey mocks base method.
func (m *MockOutboxRepository) CheckIdempotencyKey(ctx context.Context, idempotencyKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIdempotencyKey", ctx, idempotencyKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIdempotencyKey indicates an expected call of CheckIdempotencyKey.
func (mr *MockOutboxRepositoryMockRecorder) CheckIdempotencyKey(ctx, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIdempotencyKey", reflect.TypeOf((*MockOutboxRepository)(nil).CheckIdempotencyKey), ctx, idempotencyKey)
}

// GetPendingEvents mocks base method.
func (m *MockOutboxRepository) GetPendingEvents(ctx context.Context, limit int) ([]ports.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingEvents", ctx, limit)
	ret0, _ := ret[0].([]ports.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingEvents indicates an expected call of GetPendingEvents.
func (mr *MockOutboxRepositoryMockRecorder) GetPendingEvents(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingEvents", reflect.TypeOf((*MockOutboxRepository)(nil).GetPendingEvents), ctx, limit)
}

// MarkAsFailed mocks base method.
func (m *MockOutboxRepository) MarkAsFailed(ctx context.Context, eventID int64, retryCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailed", ctx, eventID, retryCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailed indicates an expected call of MarkAsFailed.
func (mr *MockOutboxRepositoryMockRecorder) MarkAsFailed(ctx, eventID, retryCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkAsFailed), ctx, eventID, retryCount)
}

// MarkAsPublished mocks base method.
func (m *MockOutboxRepository) MarkAsPublished(ctx context.Context, eventID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPublished", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPublished indicates an expected call of MarkAsPublished.
func (mr *MockOutboxRepositoryMockRecorder) MarkAsPublished(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPublished", reflect.TypeOf((*MockOutboxRepository)(nil).MarkAsPublished), ctx, eventID)
}

// MoveToDLQ mocks base method.
func (m *MockOutboxRepository) MoveToDLQ(ctx context.Context, eventID int64, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToDLQ", ctx, eventID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveToDLQ indicates an expected call of MoveToDLQ.
func (mr *MockOutboxRepositoryMockRecorder) MoveToDLQ(ctx, eventID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToDLQ", reflect.TypeOf((*MockOutboxRepository)(nil).MoveToDLQ), ctx, eventID, reason)
}

// SaveEvent mocks base method.
func (m *MockOutboxRepository) SaveEvent(ctx context.Context, event *ports.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEvent indicates an expected call of SaveEvent.
func (mr *MockOutboxRepositoryMockRecorder) SaveEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEvent", reflect.TypeOf((*MockOutboxRepository)(nil).SaveEvent), ctx, event)
}
