// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/ports/domain_event_publisher.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/ports/domain_event_publisher.go -destination=mocks/mock_domain_event_publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "product_service/products/internal/domain"
	ports "product_service/products/internal/usecase/ports"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDomainEventPublisher is a mock of DomainEventPublisher interface.
type MockDomainEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockDomainEventPublisherMockRecorder
	isgomock struct{}
}

// MockDomainEventPublisherMockRecorder is the mock recorder for MockDomainEventPublisher.
type MockDomainEventPublisherMockRecorder struct {
	mock *MockDomainEventPublisher
}

// NewMockDomainEventPublisher creates a new mock instance.
func NewMockDomainEventPublisher(ctrl *gomock.Controller) *MockDomainEventPublisher {
	mock := &MockDomainEventPublisher{ctrl: ctrl}
	mock.recorder = &MockDomainEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainEventPublisher) EXPECT() *MockDomainEventPublisherMockRecorder {
	return m.recorder
}

// PublishDomainEvent mocks base method.
func (m *MockDomainEventPublisher) PublishDomainEvent(ctx context.Context, event domain.DomainEvent, outboxRepo ports.OutboxRepository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDomainEvent", ctx, event, outboxRepo)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDomainEvent indicates an expected call of PublishDomainEvent.
func (mr *MockDomainEventPublisherMockRecorder) PublishDomainEvent(ctx, event, outboxRepo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDomainEvent", reflect.TypeOf((*MockDomainEventPublisher)(nil).PublishDomainEvent), ctx, event, outboxRepo)
}

// PublishDomainEventWithIdempotencyKey mocks base method.
func (m *MockDomainEventPublisher) PublishDomainEventWithIdempotencyKey(ctx context.Context, event domain.DomainEvent, idempotencyKey string, outboxRepo ports.OutboxRepository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDomainEventWithIdempotencyKey", ctx, event, idempotencyKey, outboxRepo)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDomainEventWithIdempotencyKey indicates an expected call of PublishDomainEventWithIdempotencyKey.
func (mr *MockDomainEventPublisherMockRecorder) PublishDomainEventWithIdempotencyKey(ctx, event, idempotencyKey, outboxRepo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDomainEventWithIdempotencyKey", reflect.TypeOf((*MockDomainEventPublisher)(nil).PublishDomainEventWithIdempotencyKey), ctx, event, idempotencyKey, outboxRepo)
}
