// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/ports/retry.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/ports/retry.go -destination=mocks/mock_retry.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	ports "product_service/products/internal/usecase/ports"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRetrier is a mock of Retrier interface.
type MockRetrier struct {
	ctrl     *gomock.Controller
	recorder *MockRetrierMockRecorder
	isgomock struct{}
}

// MockRetrierMockRecorder is the mock recorder for MockRetrier.
type MockRetrierMockRecorder struct {
	mock *MockRetrier
}

// NewMockRetrier creates a new mock instance.
func NewMockRetrier(ctrl *gomock.Controller) *MockRetrier {
	mock := &MockRetrier{ctrl: ctrl}
	mock.recorder = &MockRetrierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetrier) EXPECT() *MockRetrierMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockRetrier) Do(ctx context.Context, cfg ports.RetryConfig, fn func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, cfg, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockRetrierMockRecorder) Do(ctx, cfg, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockRetrier)(nil).Do), ctx, cfg, fn)
}
