// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/ports/event_publisher.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/ports/event_publisher.go -destination=mocks/mock_event_publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventPublisher)(nil).Close))
}

// PublishProductCreated mocks base method.
func (m *MockEventPublisher) PublishProductCreated(ctx context.Context, productID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProductCreated", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishProductCreated indicates an expected call of PublishProductCreated.
func (mr *MockEventPublisherMockRecorder) PublishProductCreated(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProductCreated", reflect.TypeOf((*MockEventPublisher)(nil).PublishProductCreated), ctx, productID)
}

// PublishProductDeleted mocks base method.
func (m *MockEventPublisher) PublishProductDeleted(ctx context.Context, productID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProductDeleted", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishProductDeleted indicates an expected call of PublishProductDeleted.
func (mr *MockEventPublisherMockRecorder) PublishProductDeleted(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProductDeleted", reflect.TypeOf((*MockEventPublisher)(nil).PublishProductDeleted), ctx, productID)
}

// MockEventPublisherHealthChecker is a mock of EventPublisherHealthChecker interface.
type MockEventPublisherHealthChecker struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherHealthCheckerMockRecorder
	isgomock struct{}
}

// MockEventPublisherHealthCheckerMockRecorder is the mock recorder for MockEventPublisherHealthChecker.
type MockEventPublisherHealthCheckerMockRecorder struct {
	mock *MockEventPublisherHealthChecker
}

// NewMockEventPublisherHealthChecker creates a new mock instance.
func NewMockEventPublisherHealthChecker(ctrl *gomock.Controller) *MockEventPublisherHealthChecker {
	mock := &MockEventPublisherHealthChecker{ctrl: ctrl}
	mock.recorder = &MockEventPublisherHealthCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisherHealthChecker) EXPECT() *MockEventPublisherHealthCheckerMockRecorder {
	return m.recorder
}

// IsHealthy mocks base method.
func (m *MockEventPublisherHealthChecker) IsHealthy(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHealthy", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHealthy indicates an expected call of IsHealthy.
func (mr *MockEventPublisherHealthCheckerMockRecorder) IsHealthy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHealthy", reflect.TypeOf((*MockEventPublisherHealthChecker)(nil).IsHealthy), ctx)
}
