// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/ports/unit_of_work.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/ports/unit_of_work.go -destination=mocks/mock_unit_of_work.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	ports "product_service/products/internal/usecase/ports"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUnitOfWork is a mock of UnitOfWork interface.
type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
	isgomock struct{}
}

// MockUnitOfWorkMockRecorder is the mock recorder for MockUnitOfWork.
type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

// NewMockUnitOfWork creates a new mock instance.
func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockUnitOfWork) Begin(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockUnitOfWorkMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockUnitOfWork)(nil).Begin), ctx)
}

// Commit mocks base method.
func (m *MockUnitOfWork) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockUnitOfWorkMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockUnitOfWork)(nil).Commit))
}

// OutboxRepository mocks base method.
func (m *MockUnitOfWork) OutboxRepository() ports.OutboxRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxRepository")
	ret0, _ := ret[0].(ports.OutboxRepository)
	return ret0
}

// OutboxRepository indicates an expected call of OutboxRepository.
func (mr *MockUnitOfWorkMockRecorder) OutboxRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxRepository", reflect.TypeOf((*MockUnitOfWork)(nil).OutboxRepository))
}

// ProductRepository mocks base method.
func (m *MockUnitOfWork) ProductRepository() ports.ProductRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProductRepository")
	ret0, _ := ret[0].(ports.ProductRepository)
	return ret0
}

// ProductRepository indicates an expected call of ProductRepository.
func (mr *MockUnitOfWorkMockRecorder) ProductRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProductRepository", reflect.TypeOf((*MockUnitOfWork)(nil).ProductRepository))
}

// Rollback mocks base method.
func (m *MockUnitOfWork) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockUnitOfWorkMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockUnitOfWork)(nil).Rollback))
}

// Transaction mocks base method.
func (m *MockUnitOfWork) Transaction() *sql.Tx {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction")
	ret0, _ := ret[0].(*sql.Tx)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockUnitOfWorkMockRecorder) Transaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockUnitOfWork)(nil).Transaction))
}
